// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"akadia/internal/auth"
	"akadia/internal/master/repository"
	"akadia/internal/master/service"
	"akadia/internal/payment/handler"
	repository2 "akadia/internal/payment/repository"
	service2 "akadia/internal/payment/service"
	"akadia/internal/platform/middleware"
)

// Injectors from wire.go:

func IntializedApplication() *Application {
	appConfig := LoadConfig()
	appConfigProvider := NewAppConfig(appConfig)
	middlewareManager := middleware.NewMiddlewareManager(appConfigProvider)
	db := NewDatabase(appConfigProvider)
	repositoryManagerMaster := repository.NewAuthRepositoryManagerMaster(db)
	userService := service.NewUserService(repositoryManagerMaster)
	userTenantRoleService := service.NewUserTenantRoleService(repositoryManagerMaster)
	studentService := service.NewStudentService(repositoryManagerMaster)
	tenantService := service.NewTenantService(repositoryManagerMaster)
	authService := auth.NewAuthService(appConfigProvider, userService, userTenantRoleService, studentService, tenantService)
	authHandler := auth.NewAuthHandler(authService)
	repositoryManagerPayment := repository2.NewAuthRepositoryManagerPayment(db)
	paymentProductService := service2.NewPaymentProductService(repositoryManagerPayment)
	paymentProductHandler := handler.NewPaymentProductHandler(paymentProductService)
	paymentPolicyService := service2.NewPaymentPolicyService(repositoryManagerPayment)
	paymentPolicyHandler := handler.NewPaymentPolicyHandler(paymentPolicyService)
	engine := NewRouter(middlewareManager, authHandler, paymentProductHandler, paymentPolicyHandler)
	application := NewApplication(engine, appConfigProvider)
	return application
}
