// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

// Injectors from wire.go:

func IntializedApplication() *Application {
	engine := NewRouter()
	appConfig := LoadConfig()
	application := NewApplication(engine, appConfig)
	return application
}
