// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"akadia/internal/auth"
	"akadia/internal/master/repository"
	"akadia/internal/master/service"
	"akadia/plarform/middleware"
)

// Injectors from wire.go:

func IntializedApplication() *Application {
	appConfig := LoadConfig()
	appConfigProvider := NewAppConfig(appConfig)
	middlewareManager := middleware.NewMiddlewareManager(appConfigProvider)
	db := NewDatabase()
	repositoryManagerMaster := repository.NewAuthRepositoryManagerMaster(db)
	userService := service.NewUserService(repositoryManagerMaster)
	userTenantRoleService := service.NewUserTenantRoleService(repositoryManagerMaster)
	studentService := service.NewStudentService(repositoryManagerMaster)
	tenantService := service.NewTenantService(repositoryManagerMaster)
	authService := auth.NewAuthService(appConfigProvider, userService, userTenantRoleService, studentService, tenantService)
	authHandler := auth.NewAuthHandler(authService)
	engine := NewRouter(middlewareManager, authHandler)
	application := NewApplication(engine, appConfigProvider)
	return application
}
